services:
  magic_pinecone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: magic_pinecone_backend
    command: sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/.venv
    expose:
      - "8000"
    networks:
      - public_net
      - app_net
      - db_net
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  dgr-h2db-detect:
    container_name: dgr-h2db-detect
    image: bash
    volumes:
      - ./db:/opt/db
      - shared:/opt/shared
    networks:
      - app_net
    command: |
      bash -c '
      cat << EOF > /opt/shared/dgr.args
      -Xms2g
      -Xmx4g
      -DdigiRunner.token.key-store.path=/opt/digirunner/keys
      -Dserver.port=18080
      -Dspring.datasource.url=jdbc:h2:/opt/digirunner/db/dgrdb;NON_KEYWORDS=VALUE;Mode=MySQL
      EOF
      ls /opt/db/*.db &> /dev/null && echo "-Dspring.sql.init.mode=never" >> /opt/shared/dgr.args || echo "-Dspring.sql.init.mode=always" >> /opt/shared/dgr.args;
      cat /opt/shared/dgr.args
      '

  dgr:
    image: tpisoftwareopensource/digirunner-open-source:release-v4.7.3
    container_name: dgr-gateway
    depends_on:
      magic_pinecone:
        condition: service_started
      dgr-h2db-detect:
        condition: service_completed_successfully
    expose:
      - "18080"
    environment:
      - TZ=Asia/Taipei
    command:
      - "@/opt/shared/dgr.args"
      - "org.springframework.boot.loader.launch.PropertiesLauncher"
    volumes:
      - ./db:/opt/digirunner/db
      - shared:/opt/shared
    networks:
      - public_net
      - app_net
    restart: unless-stopped



  db:
    image: pgvector/pgvector:pg17
    container_name: magic_pinecone_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/
    expose:
      - "5432"
    networks:
      - db_net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  adminer:
    image: adminer:5.4.2
    container_name: magic_pinecone_adminer
    expose:
      - "8080"
    networks:
      - public_net
      - db_net
    depends_on:
      - db

  caddy:
    image: caddy:2.9.1-alpine
    container_name: magic_pinecone_caddy
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "18080:18080"
      - "8081:8081"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - public_net
    depends_on:
      - magic_pinecone
      - dgr
      - adminer

networks:
  public_net:
    driver: bridge
  app_net:
    driver: bridge
  db_net:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  shared:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
