"""Initial_migration

Revision ID: 298a20ef0169
Revises: 
Create Date: 2026-05-15 12:31:31.420179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '298a20ef0169'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colleges',
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_colleges_name'), 'colleges', ['name'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content_summary', sa.Text(), nullable=True),
    sa.Column('download_link', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_category'), 'scholarships', ['category'], unique=False)
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_course_sync', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_scholarship_sync', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('college_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['college_name'], ['colleges.name'], ),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_index(op.f('ix_departments_name'), 'departments', ['name'], unique=False)
    op.create_table('courses',
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('class_no', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('credit', sa.Float(), nullable=False),
    sa.Column('password_card', sa.String(), nullable=True),
    sa.Column('teachers', sa.Text(), nullable=True),
    sa.Column('class_times', sa.Text(), nullable=True),
    sa.Column('limit_cnt', sa.Integer(), nullable=True),
    sa.Column('admit_cnt', sa.Integer(), nullable=True),
    sa.Column('wait_cnt', sa.Integer(), nullable=True),
    sa.Column('college_name', sa.String(), nullable=True),
    sa.Column('department_name', sa.String(), nullable=True),
    sa.Column('course_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['college_name'], ['colleges.name'], ),
    sa.ForeignKeyConstraint(['department_name'], ['departments.name'], ),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_index(op.f('ix_courses_class_no'), 'courses', ['class_no'], unique=False)
    op.create_index(op.f('ix_courses_serial_no'), 'courses', ['serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_serial_no'), table_name='courses')
    op.drop_index(op.f('ix_courses_class_no'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_departments_name'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    op.drop_index(op.f('ix_scholarships_category'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_colleges_name'), table_name='colleges')
    op.drop_table('colleges')
    # ### end Alembic commands ###
