"""add_course_details

Revision ID: cf0848b8624d
Revises: 8d4ef55a141e
Create Date: 2026-05-26 21:00:07.733749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf0848b8624d'
down_revision: Union[str, Sequence[str], None] = '8d4ef55a141e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_details',
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('books', sa.Text(), nullable=True),
    sa.Column('teaching_method', sa.Text(), nullable=True),
    sa.Column('grading_policy', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['serial_no'], ['courses.serial_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serial_no')
    )
    op.create_index(op.f('ix_course_details_serial_no'), 'course_details', ['serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_details_serial_no'), table_name='course_details')
    op.drop_table('course_details')
    # ### end Alembic commands ###
