"""add_course_embeddings_table

Revision ID: e3d41f3d8a7c
Revises: cf0848b8624d
Create Date: 2026-05-27 14:30:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'e3d41f3d8a7c'
down_revision: Union[str, Sequence[str], None] = 'cf0848b8624d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_embeddings',
    sa.Column('serial_no', sa.String(), nullable=False),
    sa.Column('organized_description', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=768), nullable=True),
    sa.ForeignKeyConstraint(['serial_no'], ['courses.serial_no'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('serial_no')
    )

    op.create_index(op.f('ix_course_embeddings_serial_no'), 'course_embeddings', ['serial_no'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_embeddings_serial_no'), table_name='course_embeddings')
    op.drop_table('course_embeddings')
    # ### end Alembic commands ###
