"""add_user_details

Revision ID: e865e294048d
Revises: 02a827ad21ba
Create Date: 2026-05-28 05:28:48.672581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e865e294048d'
down_revision: Union[str, Sequence[str], None] = '02a827ad21ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('study_system', sa.String(), nullable=True))
    op.add_column('users', sa.Column('student_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employee_type', sa.String(), nullable=True))
    op.add_column('users', sa.Column('employee_status', sa.String(), nullable=True))
    op.add_column('users', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'title')
    op.drop_column('users', 'employee_status')
    op.drop_column('users', 'employee_type')
    op.drop_column('users', 'student_status')
    op.drop_column('users', 'study_system')
    # ### end Alembic commands ###
